CPU = 2
MEMORY = 2048
SERVER_HOST_NAME = "HdagdaguS"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.define SERVER_HOST_NAME do |server|
        server.vm.hostname = SERVER_HOST_NAME
        server.vm.network "private_network", ip: SERVER_IP
        server.vm.network "forwarded_port", guest: 6443, host: 6443
        server.vm.network "forwarded_port", guest: 80, host: 80

        server.vm.provider "virtualbox" do |vm|
            vm.memory = MEMORY
            vm.cpus = CPU
            vm.name = SERVER_HOST_NAME
        end
        server.vm.provision "shell", path: "./scripts/hdagdagu_server_setup.sh", args: [SERVER_IP]
    end
end