# end: "This is where the block ends."


# Shared settings for both machines
CPU = 1
MEMORY = 1024

# Machine names (using'doffa' as your login)
SERVER_NAME = "HdagdaguS"
WORKER_NAME = "HdagdaguSW"

# Server and Worker IP addresses
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"


# Vagrant.configure("2"): A method (function) that says "I want to configure Vagrant using version 2."
# do |config|: "Start a block of code, and give me a variable called config to use inside."

Vagrant.configure("2") do |config|

    # We tell Vagrant which box (base image) to use for the virtual machines.
    config.vm.box = "bento/ubuntu-22.04"

    # Define the server machine
    config.vm.define SERVER_NAME do |server|
        server.vm.hostname = SERVER_NAME
        server.vm.network "private_network", ip: SERVER_IP
        server.vm.network "forwarded_port", guest: 6443, host: 6443

        server.vm.provider "virtualbox" do |vb|
            vb.name = SERVER_NAME
            vb.cpus = CPU
            vb.memory = MEMORY
        end

        server.vm.provision "shell", path: "./scripts/k3s_server_config.sh", args: [SERVER_IP]
    end


    # Define the worker machine
    config.vm.define WORKER_NAME do |worker|
        worker.vm.hostname = WORKER_NAME
        worker.vm.network "private_network", ip: WORKER_IP

        worker.vm.provider "virtualbox" do |vb|
            vb.name = WORKER_NAME
            vb.cpus = CPU
            vb.memory = MEMORY
        end

        worker.vm.provision "shell", path: "./scripts/k3s_agent_config.sh", args: [SERVER_IP, SERVER_NAME]
    end
end